# Generated by Django 5.2 on 2025-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apt', models.CharField(max_length=5)),
                ('nome_morado', models.CharField(max_length=150)),
            ],
        ),
    ]
