# Generated by Django 5.2 on 2025-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastros',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
